Repository wizzie-io/zz-cep, pull requests merged in 2018-12, with the labels that each got.

#13 Add logo print to zz-cep
  service/src/main/java/io/wizzie/cep/Cep.java
  service/src/main/java/io/wizzie/cep/logo/LogoPrinter.java
Labels: improvement

#14 Fix deploy
  .circleci/config.yml
Labels: test

#15 Fix bootstrapper.classname at docker config_env.json
  docker/build/config_env.json
Labels: bug

#16 Fix circle deploy
  .circleci/config.yml
Labels: test

#17 Add host into metric databag
  service/src/main/java/io/wizzie/cep/builder/Builder.java
  service/src/main/java/io/wizzie/cep/utils/Utils.java
Labels: improvement
